export enum StoreEnum {
	ADD_POST = 'ADD_POST',
    UPDATE_NEW_POST_TEXT = 'UPDATE_NEW_POST_TEXT',

    ADD_MESSAGE = 'ADD_MESSAGE',
    UPDATE_MESSAGE = 'UPDATE_MESSAGE',

    USER_SUBSCRIBE = 'USER_SUBSCRIBE',
    USER_UNSUBSCRIBE = 'USER_UNSUBSCRIBE',

    SET_USERS = 'SET_USERS'
}