export enum StoreEnum {
  ADD_POST = 'ADD_POST',
  ADD_MESSAGE = 'ADD_MESSAGE',
  USER_SUBSCRIBE = 'USER_SUBSCRIBE',
  USER_UNSUBSCRIBE = 'USER_UNSUBSCRIBE',

  SET_USERS = 'SET_USERS',
  SET_CURRENT_PAGE = 'SET_CURRENT_PAGE',
  SET_TOTAL_USERS_COUNT = 'SET_TOTAL_USERS_COUNT',

  TOGGLE_IS_FETCHING = 'TOGGLE_IS_FETCHING',
  TOGGLE_IS_SUBSCRIBING_PROGRESS = 'TOGGLE_IS_SUBSCRIBING_PROGRESS',

  SET_PROFILE = 'SET_PROFILE',
  SET_MY_PROFILE = 'SET_MY_PROFILE',

  SET_USER_DATA = 'SET_USER_DATA',
  SET_AUTH_USER = 'SET_AUTH_USER',

  GET_USERS_STATUS = 'GET_USERS_STATUS',
  UPDATE_MY_STATUS = 'UPDATE_MY_STATUS',
  SAVE_PHOTO_SUCCESS = 'SAVE_PHOTO_SUCCESS',

  SET_INITIALIZED = 'SET_INITIALIZED',
  INITIALIZED_SUCCESS = 'INITIALIZED_SUCCESS'
}
